dist: xenial   # required for Python >= 3.7
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION='>=1.9,<1.10'
  - DJANGO_VERSION='>=1.10,<1.11'
  - DJANGO_VERSION='>=1.11,<1.12'
install:
  - "pip install Django$DJANGO_VERSION"
  - "pip install -r tests_requirements.txt"
  - "python setup.py install"
script:
  - "coverage run --source=popolo runtests.py"
after_script:
  - coveralls --verbose
